(()=>{
 const brief=window.StatPigDaily,guide=window.StatPigGuide,{esc}=SP;
 if(!brief||!guide||brief.week!==guide.week||brief.season!==guide.season)return;
 document.querySelectorAll('.weekbox').forEach(el=>{el.innerHTML=`<span>${esc(guide.season)} Season</span><strong>Week ${esc(guide.week)}</strong>`;});
 const when=x=>new Date(x).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'});
 const key=`statpig-research-list-${guide.season}-${guide.week}`,seenKey='statpig-last-brief';
 let saved=[];try{const a=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(a))saved=a.filter(x=>typeof x==='string');}catch{}
 const match=id=>guide.games.find(g=>g.scheduleId===id),link=id=>`guide.html#game-${encodeURIComponent(match(id)?.id||'')}`;
 const checkedLink=(url,label)=>{try{if(new URL(url).protocol==='https:')return `<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`;}catch{}return '';};
 let lastSeen=null;try{lastSeen=localStorage.getItem(seenKey);}catch{}
 const old=Date.now()-Date.parse(brief.reviewedAt)>86400000,started=guide.games.every(g=>Date.now()>=Date.parse(g.kickoffAt));
 const editionNote=started?'Archived pregame edition. These games have started; use this as a record of earlier research.':old?'This edition is more than 24 hours old. Recheck the linked reports before using its availability assumptions.':'Current published edition. Individual prices and injury reports still require rechecking.';
 const stories=brief.stories.map(s=>`<article class="panel daily-story"><p class="eyebrow">${esc(s.tag)}</p><h3>${esc(s.title)}</h3><p>${esc(s.text)}</p><a href="${link(s.game)}">Read the game →</a>${s.source?`<p>${checkedLink(s.source,'Official source')}</p>`:''}</article>`).join('');
 function renderList(){const box=document.getElementById('my-game-list');if(!box)return;const games=guide.games.filter(g=>saved.includes(g.scheduleId));box.innerHTML=games.length?games.map(g=>`<a class="saved-game" href="guide.html#game-${encodeURIComponent(g.id)}"><b>${esc(g.away)} at ${esc(g.home)}</b><span>${esc(when(g.kickoffAt))}</span><span>${esc(g.headline)}</span></a>`).join(''):'<p>No games saved yet. Choose the matchups you want to revisit below.</p>';document.querySelectorAll('[data-save-game]').forEach(b=>{const on=saved.includes(b.dataset.saveGame);b.setAttribute('aria-pressed',String(on));b.textContent=(on?'✓ Saved: ':'+ Save: ')+b.dataset.label;});}
 const home=document.getElementById('daily-desk'),full=document.getElementById('daily-content');
 const header=`<div class="section-head"><div><p class="eyebrow">THE DAILY DESK · WEEK ${esc(guide.week)}</p><h2>Your two-minute NFL briefing</h2></div>${home?'<a class="button-outline" href="daily.html">Open the Daily Desk →</a>':''}</div><p class="daily-deck">${esc(brief.headline)}</p><p class="guide-time">Reviewed ${esc(when(brief.reviewedAt))} · ${esc(editionNote)}</p><p class="daily-return">${lastSeen&&Date.parse(lastSeen)<Date.parse(brief.reviewedAt)?'A newer editorial edition is available since your previous visit.':lastSeen?'You have already seen this editorial edition. A new visit does not mean the research has changed.':'Start with the news, then inspect the price and the competing game script.'}</p>`;
 const notebook=`<section class="panel daily-notebook"><p class="eyebrow">THE IDEA NOTEBOOK</p><h3>What held up. What weakened. What needs work.</h3>${brief.notebook.map(n=>{const g=match(n.game);return `<div class="notebook-row"><h4>${esc(g?g.away+' at '+g.home:'Matchup unavailable in this edition')}</h4><p><b>${esc(n.idea||'Research idea')}</b>${g?` · ${esc(when(g.kickoffAt))}`:''}</p><span class="guide-tag">${esc(n.label)}</span><p><b>Original idea:</b> ${esc(n.originalIdea||'Earlier reasoning was not retained in this edition.')}</p><p><b>Current assessment:</b> ${esc(n.text)}</p>${g?`<a href="${link(n.game)}">Read the ${esc(g.away+'–'+g.home)} analysis →</a>`:''}</div>`;}).join('')}<small>Editorial updates only. These are not formal WATCH, BET or graded paper picks.</small></section>`;
 if(home)home.innerHTML=header+`<div class="daily-stories">${stories}</div>`+notebook;
 if(full){full.innerHTML=header+`<p class="guide-notice">${esc(brief.notice)}</p><div class="daily-stories">${stories}</div>`+notebook+`<section class="panel daily-watchlist"><p class="eyebrow">YOUR RESEARCH SHORTLIST</p><h2>Keep your games close</h2><p>Save matchups for your next visit. Stored only in this browser on this device; no account, tracking service or push alerts.</p><div id="my-game-list" aria-live="polite"></div><details><summary>Choose or remove games</summary><div class="save-grid">${guide.games.map(g=>`<button type="button" class="button-outline" data-save-game="${esc(g.scheduleId)}" data-label="${esc(g.away+' at '+g.home)}" aria-pressed="false">Save game</button>`).join('')}</div></details><p id="save-status" role="status"></p></section><section class="panel daily-value"><p class="eyebrow">TODAY’S PRICE LESSON</p><h2>The line and the odds are two different prices</h2><p>Taking +3 protects a three-point loss; +2.5 does not. But paying more juice for the extra half-point also raises your break-even rate. At -110 you need 52.38% wins among non-push outcomes to break even; at -120 you need 54.55%.</p><p>A better number is worth examining, not buying at any cost. The Game Guide groups identical selections and lines, so you can compare the odds without mixing different contracts.</p><a href="guide.html#price-desk">Compare this edition’s exact contracts →</a></section><section class="daily-rhythm"><p class="eyebrow">A REASON TO LOOK AGAIN</p><h2>What matters each day</h2><p>This is the research rhythm—not a promise that a new edition has been published. Check the timestamp above.</p><div class="rhythm-grid">${brief.rhythm.map(r=>`<article class="panel mini"><p class="eyebrow">${esc(r.day)}</p><h3>${esc(r.title)}</h3><p>${esc(r.text)}</p></article>`).join('')}</div></section>`;
 document.querySelectorAll('[data-save-game]').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.saveGame;saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];try{localStorage.setItem(key,JSON.stringify(saved));document.getElementById('save-status').textContent='Research shortlist saved on this device.';}catch{document.getElementById('save-status').textContent='Browser storage is unavailable; this list will last only for this visit.';}renderList();}));renderList();}
 const props=document.getElementById('prop-questions');if(props)props.innerHTML=`<div class="section-head"><div><p class="eyebrow">WEEK ${esc(guide.week)} · ROLE BEFORE PRICE</p><h2>Player-prop questions worth asking</h2></div></div><p>No priced prop recommendations are asserted here. These are matchup-specific questions to investigate before choosing a player or direction.</p><div class="rhythm-grid">${guide.games.filter(g=>g.propResearch).map(g=>`<article class="panel mini"><h3>${esc(g.away)} at ${esc(g.home)}</h3><p>${esc(g.propResearch)}</p><a href="guide.html#game-${encodeURIComponent(g.id)}">Full game context →</a></article>`).join('')}</div>`;
 if(home||full)try{localStorage.setItem(seenKey,brief.reviewedAt);}catch{}
})();
