(()=>{
 const d=window.StatPigGuide,{esc,signed}=SP;
 const when=x=>x?new Date(x).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}):'Not captured';
 const profit=o=>o>0?o/100:100/-o;
 const freshness=(at,kickoff)=>Date.now()<Date.parse(kickoff)&&Date.now()>=Date.parse(at)&&Date.now()-Date.parse(at)<=1200000;
 const selection=q=>q.kind==='side'?`${q.subject} ${signed(q.line)}`:`${q.direction} ${q.line} ${q.market==='total_points'?'points':q.market}`;
 const sourceLink=s=>/^https:\/\//.test(s.url||'')?`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.label)}</a>`:esc(s.label);
 function prices(g){return `<div class="table-wrap"><table class="guide-prices"><thead><tr><th>Exact selection</th><th>Captured prices</th><th>Comparison</th></tr></thead><tbody>${g.comparisons.map(q=>{
  const fresh=q.rows.filter(r=>freshness(r.observedAt,g.kickoffAt)),pool=fresh.length?fresh:q.rows,best=Math.max(...pool.map(r=>profit(r.odds))),winners=pool.filter(r=>profit(r.odds)===best),diff=100*(best-Math.min(...pool.map(r=>profit(r.odds))));
  return `<tr><td>${esc(selection(q))}</td><td>${q.rows.map(r=>`<div><b>${esc(r.book)} ${esc(signed(r.odds))}</b><br><small>${esc(when(r.observedAt))} · <span data-price-at="${esc(r.observedAt)}" data-kickoff="${esc(g.kickoffAt)}">${freshness(r.observedAt,g.kickoffAt)?'Within 20-minute window':'Historical / recheck required'}</span></small></div>`).join('')}</td><td>Best price in the comparison: ${esc(winners.map(r=>r.book).join(' / '))}${pool.length>1&&diff>0?`<br><small>$${diff.toFixed(2)} more profit per $100 risked if it wins, versus the worse listed price.</small>`:''}${pool.length===1?'<br><small>Only one comparable quote; no cross-book advantage established.</small>':''}</td></tr>`;
 }).join('')}</tbody></table></div>`;}
 const article=g=>`<article class="panel guide-game" id="game-${esc(g.id)}" data-matchup="${esc((g.away+' '+g.home).toLowerCase())}"><div class="guide-game-top"><p class="eyebrow">${esc(when(g.kickoffAt))}</p><span class="guide-tag">MATCHUP RESEARCH</span></div><h2>${esc(g.away)} at ${esc(g.home)}</h2><h3 class="guide-angle">${esc(g.headline)}</h3><p class="guide-time">Editorial reviewed ${esc(when(g.editorialAt))} · Injury table checked ${esc(when(g.injuryObservedAt))}</p><div class="guide-prose">${g.paragraphs.map(p=>`<section><h4>${esc(p.title)}</h4><p>${esc(p.text)}</p></section>`).join('')}</div><details><summary>Compare spread and total prices</summary><p class="bodycopy">Same selection and same line are compared together. A different line is a different contract. These are captured quotes from the listed books, not guaranteed available prices. A better price does not establish a positive expected return.</p>${prices(g)}</details><details><summary>Injury designations and source notes</summary><p class="bodycopy">Observed ${esc(when(g.injuryObservedAt))}; source publication time ${g.injuryPublishedAt?esc(when(g.injuryPublishedAt)):'not supplied'}. This rolling table is not the final inactive list. Blank designations are omitted and do not prove availability.</p><ul class="guide-injuries">${g.players.map(p=>`<li><b>${esc(p.name)}</b> · ${esc(p.team)} · ${esc(p.position)} — ${esc(p.status)}<br><small>${esc(p.injury||'Injury detail not supplied')} · practice: ${esc(p.participation||'not supplied')}</small></li>`).join('')||'<li>No explicit designations captured.</li>'}</ul><ul class="guide-sources">${g.sources.map(s=>`<li>${sourceLink(s)} · checked ${esc(when(s.observedAt))}${s.publishedAt?' · issued '+esc(when(s.publishedAt)):''}</li>`).join('')}</ul></details><div class="guide-checkpoint"><b>Next checks</b>${g.checkpoints.map(c=>`<div>${esc(when(c.at))} — ${esc(c.label)}</div>`).join('')}<small>These are research checkpoints, not confirmation that an update has been completed.</small></div><a href="game.html?id=${encodeURIComponent(g.id)}">Open model audit →</a></article>`;
 function updates(){return d.changes.length?[...d.changes].sort((a,b)=>Math.abs(b.toLine-b.fromLine)-Math.abs(a.toLine-a.fromLine)).slice(0,8).map(c=>{const g=d.games.find(g=>g.id===c.eventId);return `<li><a href="guide.html#game-${esc(c.eventId)}">${esc(g?g.away+' at '+g.home:c.subject)}</a><p>${esc(c.book)} · ${esc(c.kind==='side'?c.subject:c.direction+' total')}: ${esc(c.kind==='side'?signed(c.fromLine):c.fromLine)} (${esc(signed(c.fromOdds))}) → ${esc(c.kind==='side'?signed(c.toLine):c.toLine)} (${esc(signed(c.toOdds))})</p><small>${esc(when(c.fromAt))} → ${esc(when(c.toAt))}. Observed movement; cause not established.</small></li>`;}).join(''):'<li>No comparable quote changes recorded for this edition. First observations are a baseline, not breaking news.</li>';}
 function render(){
  const home=document.getElementById('daily-guide'),page=document.getElementById('guide-content');
  if(!d||d.schema!=='statpig-game-guide-v1'){if(home)home.textContent='The game guide is unavailable. Please check back after the next evidence refresh.';if(page)page.textContent='No verified guide export is available.';return;}
  document.querySelectorAll('.weekbox').forEach(el=>{el.innerHTML=`<span>${esc(d.season)} Season</span><strong>Week ${esc(d.week)}</strong>`;});
  const ended=d.games.every(g=>Date.now()>=Date.parse(g.kickoffAt));
  const stamp=`Edition ${esc(when(d.generatedAt))} · ${d.games.length} remaining-game previews · Times shown in your device’s timezone`;
  if(home)home.innerHTML=`<div class="section-head"><div><p class="eyebrow">THE DAILY BRIEFING</p><h2>What matters this week</h2></div><a class="button-outline" href="guide.html">Read every matchup →</a></div><p class="guide-time">${stamp}</p><div class="guide-highlights">${[...d.games].sort((a,b)=>(b.weather?.roof==='OUTDOOR'?b.weather.windMph:0)-(a.weather?.roof==='OUTDOOR'?a.weather.windMph:0)).slice(0,3).map(g=>`<a class="panel mini" href="guide.html#game-${esc(g.id)}"><p class="eyebrow">${esc(g.away)} at ${esc(g.home)}</p><h3>${esc(g.headline)}</h3><p>${esc(g.angle)}</p>${g.weather?.roof==='OUTDOOR'?`<p><b>Weather watch:</b> captured sustained wind up to ${esc(g.weather.windMph)} mph; peak hourly rain probability ${esc(g.weather.precipProbability)}%.</p>`:''}<span>Read the matchup →</span></a>`).join('')}</div><div class="guide-two"><section class="panel mini"><h3>What changed in the market</h3><ul class="guide-updates">${updates()}</ul><a href="guide.html#price-desk">Compare all captured prices →</a></section><section class="panel mini"><h3>Next on the research desk</h3><p>Official inactives, replacement roles and a fresh look at the price. Follow each game’s checkpoints in the guide.</p><p>Injury table checked ${esc(when(d.injuryObservedAt))}. Weather collected ${esc(when(d.weatherObservedAt))}.</p><p><b>Editorial analysis is available now.</b> Official BET recommendations still require the complete model review.</p><a href="research.html">Track numerical near misses →</a></section></div>`;
  if(page){page.innerHTML=`<p class="guide-time">${stamp}</p><p class="guide-notice">${ended?'Archived pregame edition. Games have started; quoted prices are historical. ':''}${esc(d.notice)}</p><div class="guide-two"><section class="panel mini"><h2>What changed</h2><ul class="guide-updates">${updates()}</ul><p>${d.changes.length} observed quote changes in this edition. Line and price moves do not prove sharp action.</p></section><section class="panel mini"><h2>Use the guide</h2><p>Read the football question, compare the same contract across books, then check what still needs confirmation.</p><label for="game-search">Find your team</label><input id="game-search" type="search" placeholder="Team name…" autocomplete="off"><p id="guide-count" aria-live="polite">${d.games.length} matchups</p><p>Already-played games are not reconstructed into pregame opinions. Postgame reviews require verified results and the original archived edition.</p></section></div><section id="price-desk"><h2>The full matchup guide</h2><p>Four perspectives on each remaining game: market, personnel, conditions and the next decision. Expand a game’s price comparison for exact lines, books and timestamps.</p></section><div id="guide-games">${d.games.map(article).join('')}</div><section class="panel mini"><h2>The season-long notebook</h2><p>Each generated edition is retained privately before later updates. Postgame review will compare those original observations with verified outcomes; a new edition cannot rewrite an earlier opinion. No postgame reviews have been published in this edition.</p><p>${d.history.length} earlier guide editions retained. Official recommendations and hypothetical Near Misses have separate performance records.</p><a href="research.html">Near Misses research →</a></section>`;
   document.getElementById('game-search').addEventListener('input',e=>{const term=e.target.value.toLowerCase().trim();let count=0;document.querySelectorAll('.guide-game').forEach(el=>{el.hidden=!el.dataset.matchup.includes(term);if(!el.hidden)count++;});document.getElementById('guide-count').textContent=`${count} ${count===1?"matchup":"matchups"}`;});
  }
 }
 render();
 // Re-evaluate expired prices when a reader returns to the page.
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)render();});
 // Mark expired quotes conservatively without reloading or stealing focus.
 setInterval(()=>{document.querySelectorAll('[data-price-at]').forEach(el=>{el.textContent=freshness(el.dataset.priceAt,el.dataset.kickoff)?'Within 20-minute window':'Historical / recheck required';});},30000);
})();
