(async()=>{
 const d=await SP.load(),esc=SP.esc,rows=d.research||[],m=d.researchMetrics;
 const money=x=>Number.isFinite(x)?x.toFixed(2):'—';
 const value=(x,unit)=>unit==='fraction'?SP.pct(x):money(x)+' points';
 document.getElementById('researchKpis').innerHTML=[['Tracked near misses',rows.length],['Hypothetical record',m?`${m.wins}–${m.losses}–${m.pushes}`:'0–0–0'],['Hypothetical net units',money(m?.netUnits)],['Hypothetical ROI',SP.pct(m?.roi)],['Pending',m?.pending??0]].map(([a,b])=>`<div class="kpi"><div class="label">${esc(a)}</div><strong>${esc(b)}</strong></div>`).join('');
 document.getElementById('researchNote').textContent=m?.note||'No prospective near-miss entries have been recorded. Historical selections and incomplete analyses are not backfilled.';
 document.getElementById('researchTable').innerHTML='<thead><tr><th>Recorded selection</th><th>Why no BET?</th><th>Recorded before kickoff</th><th>Research result</th></tr></thead><tbody>'+ (rows.length?rows.map(r=>`<tr><td>${esc(SP.selection(r.quote))}<br>${esc(r.quote.book)} · ${esc(SP.signed(r.quote.odds))}<br><small>${esc(r.game)}</small></td><td>${r.reasons.map(x=>`${esc(x.gate)}: ${esc(value(x.actual,x.unit))} vs required ${esc(value(x.required,x.unit))}`).join('<br>')}<br><small>${esc(r.policy.version)} · Model ${esc(r.modelVersion)} · ${esc(r.modelSourceId||'Scenario model')}</small></td><td>${esc(SP.date(r.issuedAt))}<br><small>Kickoff ${esc(SP.date(r.kickoffAt))}</small></td><td>${esc(r.settlement?.result||'PENDING')}<br>${r.settlement?esc(money(r.settlement.profit))+' hypothetical units':''}${r.settlement?.reason?'<br>'+esc(r.settlement.reason):''}</td></tr>`).join(''):'<tr><td colspan="4">No qualifying entries yet. We do not fill this page with incomplete analyses or picks added after the result.</td></tr>')+'</tbody>';
 const gates=[...new Set(rows.flatMap(r=>r.failedGates))];
 document.getElementById('researchGroups').innerHTML=gates.length?gates.map(g=>{const rr=rows.filter(r=>r.failedGates.includes(g)),settled=rr.filter(r=>r.settlement&&r.settlement.result!=='VOID');return `<p><strong>${esc(g)}</strong>: ${rr.length} tracked; ${settled.length} settled; ${money(settled.reduce((s,r)=>s+r.settlement.profit,0))} hypothetical units.</p>`;}).join(''):'<p>Failed-gate comparisons will appear after prospective entries are recorded.</p>';
 const p=d.researchPolicy;document.getElementById('researchRules').textContent=p?`${p.version}: at most ${p.maxFailedGates} failed numerical gates; edge no more than ${p.maxEdgeShortfall} points short; estimated EV at least ${SP.pct(p.minEV)}; conditional win probability at least ${SP.pct(p.minConditionalWin)}; worst stress EV at least ${SP.pct(p.minStressEV)}. Complete audits and the price gate are mandatory. These are research inclusion limits, not relaxed BET rules.`:'Research policy is not yet present in this exported snapshot.';
 const incomplete=d.games.flatMap(g=>(g.analyses||[]).filter(a=>a.result.analysisStatus!=='COMPLETE').map(a=>({g,a})));
 document.getElementById('researchIncomplete').innerHTML=incomplete.length?incomplete.map(({g,a})=>`<details class="correction"><summary>${esc(SP.selection(a.quote))} · analysis incomplete</summary><p>${esc(g.away)} @ ${esc(g.home)}</p><ul>${(a.result.errors||[]).map(e=>`<li>${esc(e)}</li>`).join('')}</ul></details>`).join(''):'<p class="bodycopy">No incomplete candidate analyses are present in this public snapshot.</p>';
 document.getElementById('researchDownload').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({generatedAt:d.generatedAt,policy:p,records:rows,metrics:m},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='StatPig_Near_Miss_Research.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
})().catch(e=>SP.error(e.message));
