window.SP = (()=>{
 const esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const signed=x=>x>0?'+'+x:String(x);
 const pct=x=>x==null?'—':(100*x).toFixed(1)+'%';
 const date=x=>x?new Date(x).toLocaleString('en-US',{timeZone:'America/Chicago',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}):'Not recorded';
 const selection=q=>q.kind==='side'?`${q.subject} ${signed(q.line)}`:`${q.subject} — ${q.direction} ${q.line} ${q.market}`;
 const badge=x=>`<span class="status ${['BET','WATCH','PASS','FINAL','ARCHIVE'].includes(x)?x:'PASS'}">${esc(x)}</span>`;
 const active=(d)=>d.activeRecommendations.filter(r=>Date.now()<Date.parse(r.validUntil)&&Date.now()<Date.parse(r.kickoffAt)&&r.result?.decision==='BET'&&r.result.analysisStatus==='COMPLETE'&&r.result.confidence==='High');
 const recent=d=>d.marketAsOf&&Date.now()-Date.parse(d.marketAsOf)>=0&&Date.now()-Date.parse(d.marketAsOf)<=20*60000;
 const status=(g,d)=>g.state==='FINAL'?'FINAL':active(d).some(r=>r.eventId===g.id)?'BET':!g.archive&&recent(d)&&g.analyses.some(a=>a.result.decision==='WATCH'&&a.watch?.actionable&&a.watch?.kills&&Date.now()<Date.parse(g.kickoffAt))?'WATCH':'PASS';
 const market=(g,kind)=>g.quotes?.filter(q=>q.kind===kind).map(q=>`${kind==='side'?q.subject+' '+signed(q.line):q.line} (${q.book}, ${signed(q.odds)})`).join(' / ')||(g.archive?(kind==='side'?g.referenceMarket||'Withheld: conflicting archive':g.referenceTotal)+' · archived':'Not recorded');
 const why=(g,d)=>{const r=active(d).find(r=>r.eventId===g.id);if(r)return `${selection(r.quote)} at ${signed(r.quote.odds)}. Estimated win ${pct(r.result.probability.win)}; push ${pct(r.result.probability.push)}; expected return ${pct(r.result.probability.ev)} per unit. Experimental, uncalibrated.`;return g.notes?.map(n=>n.text).join(' ')||'No complete, current, reproducible analysis clears the publication gates.';};
 const evidence=(rows,sources)=>rows?.length?rows.map(a=>`<div class="correction"><h4>${esc(a.key.replace(/_/g,' '))}</h4><p class="bodycopy">${esc(a.note||'No note recorded.')}</p><small>Recorded status: ${esc(a.status)} · checked ${esc(date(a.checkedAt))}. ${a.sourceIds.map(id=>{const s=sources.find(s=>s.id===id);return s?`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a> (observed ${esc(date(s.observedAt))})`:esc(id);}).join(' · ')}</small></div>`).join(''):'<p class="bodycopy">No structured audit evidence has been recorded.</p>';
 const list=a=>a.map(x=>`<li>${esc(x)}</li>`).join('');
 const error=(message)=>{document.querySelector('main').innerHTML=`<section class="panel mini"><h2>Not found</h2><p>${esc(message)}</p><a href="index.html">Return to the dashboard</a></section>`;document.title='Not found · StatPig';};
 async function load(){let d=window.StatPigSnapshot,network='Exported snapshot';const base=window.STATPIG_CONFIG?.apiBase;
 if(base){try{const u=new URL(base);if(u.protocol!=='https:'&&!['127.0.0.1','localhost'].includes(u.hostname))throw Error('Unsafe API address');const response=await fetch(base.replace(/\/$/,'')+'/api/public',{cache:'no-store',signal:AbortSignal.timeout(5000)});if(!response.ok)throw Error('API unavailable');const x=await response.json();if(x.schemaVersion!==1||!Array.isArray(x.games))throw Error('Invalid API schema');d=x;network='Private-ledger read-only feed';}catch{network='Live feed unavailable — archived fallback only';d={...d,activeRecommendations:[],marketAsOf:null};}}
 if(!d)throw Error('No snapshot is available');d={...d,activeRecommendations:active(d)};
 const notice=document.createElement('div');notice.className='integrity-banner';notice.innerHTML=`<strong>${esc(d.mode)}</strong><span>${esc(network)} · Build ${esc(d.build)} · Model ${esc(d.model.version)}</span><p>Market as of: ${esc(date(d.marketAsOf))}. Page/export generated: ${esc(date(d.generatedAt))}. ${d.snapshotComplete?'Snapshot coverage complete; quotes still expire after 20 minutes.':'ANALYSIS INCOMPLETE — no current audited full-slate snapshot.'} An empty BET board is intentional when evidence is missing.</p>`;const features=document.querySelector('.feature-grid');if(features)features.after(notice);else document.querySelector('main').prepend(notice);
 // Refresh at the earliest quote expiration, including WATCH-only screens.
 const deadlines=[...d.activeRecommendations.map(r=>Date.parse(r.validUntil)),...(d.marketAsOf?[Date.parse(d.marketAsOf)+20*60000]:[])].filter(t=>Number.isFinite(t)&&t>Date.now());
 const deadline=deadlines.length?Math.min(...deadlines):null;
 if(deadline){setTimeout(()=>location.reload(),Math.max(25,deadline-Date.now()+25));document.addEventListener('visibilitychange',()=>{if(!document.hidden&&Date.now()>=deadline)location.reload();});}
 document.querySelectorAll('.weekbox').forEach(el=>{const g=d.games[0];el.innerHTML=`<span>${esc(g?.season||'')} Season</span><strong>Week ${esc(g?.week||'—')}</strong>`;});return d;
 }
 function resultTable(rows){return `<thead><tr><th>Issued / version</th><th>Selection / book</th><th>Units risked</th><th>Result</th><th>Net units</th><th>Closing quote</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td>${esc(date(r.issuedAt))}<br>${esc(r.modelVersion)}</td><td>${esc(selection(r.quote))}<br>${esc(r.quote.book)} · ${esc(signed(r.quote.odds))}${r.withdrawn?'<br>Withdrawn from new action; original remains tracked':r.withdrawals.length?'<br>Withdrawal history retained; current price was revalidated':''}${r.revalidations?.length?'<br>'+r.revalidations.length+' later price rechecks; original result unchanged':''}</td><td>${r.stakeUnits}</td><td>${esc(r.settlement?.result||'PENDING')}</td><td>${esc(r.settlement?.profit??'—')}</td><td>${r.close?esc(r.close.line+' / '+r.close.book):'Missing; not imputed'}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">No prospective recommendations issued. Legacy records are below, not counted as v1.1 wins.</td></tr>'}</tbody>`;}
 return {esc,signed,pct,date,selection,badge,active,recent,status,market,why,evidence,list,error,load,resultTable};
})();
