(()=>{
 const {esc}=SP;
 const when=x=>x?new Date(x).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}):'Not available';
 function state(g){const w=g.weather;if(!w||w.status==='UNAVAILABLE')return 'Forecast unavailable';if(w.status==='INDOOR')return 'Fixed roof';if(Date.now()>=Date.parse(g.kickoffAt))return 'Archived forecast';if(!Number.isFinite(Date.parse(w.issuedAt))||Date.now()<Date.parse(w.issuedAt)||Date.now()-Date.parse(w.issuedAt)>86400000)return 'Stale · refresh needed';return w.roof==='OUTDOOR'?'Outdoor forecast':w.roof==='CLOSED'?'Roof reported closed':'Roof decision unconfirmed';}
 function panel(g){const w=g.weather,s=state(g);if(!w||w.status!=='FORECAST')return `<section class="weather-panel"><h4>Game-window weather · ${esc(s)}</h4><p>${esc(w?.notice||'No verified forecast in this edition.')}</p>${w?.sourceUrl?`<a href="${esc(w.sourceUrl)}" target="_blank" rel="noopener noreferrer">Stadium source ↗</a>`:''}</section>`;
 const temp=w.temperatureF;
 return `<section class="weather-panel" id="weather-${esc(g.id)}"><p class="eyebrow">GAME-WINDOW WEATHER · <span data-weather-status="${esc(g.id)}">${esc(s)}</span></p><p>${esc(g.venueName)} · ${esc(when(w.validFrom))} through ${esc(when(w.validTo))}</p><div class="weather-metrics"><div><b>${temp?esc(Math.round(temp.kickoff))+'°F':'Unavailable'}</b><small>Kickoff temperature${temp?` · ${esc(Math.round(temp.min))}–${esc(Math.round(temp.max))}°F during game`:''}</small></div><div><b>${esc(w.windMph)} mph</b><small>Peak sustained wind · ${esc(w.windDirections?.join(' / ')||'direction unavailable')}</small></div><div><b>${esc(w.precipProbability)}%</b><small>Peak hourly precipitation chance</small></div></div><p>Gusts: not supplied by this hourly feed. Precipitation probability is not intensity or the chance of rain over the entire game.</p><p>${w.roof==='OUTDOOR'?'Watch for forecast changes before evaluating passing, kicking or totals. These observations alone establish no betting edge.':'Outside-stadium conditions only. Do not apply these wind or rain figures to the playing field while the roof is closed or its status is unconfirmed.'}</p><small>Forecast issued ${esc(when(w.issuedAt))} · Collected ${esc(when(w.observedAt))}. This page shows the last published collection, not a live feed.</small><p>${w.changes?.length?w.changes.map(c=>`${esc(c.label)}: ${esc(c.from)} → ${esc(c.to)} ${esc(c.unit)} (previous forecast ${esc(when(c.fromAt))})`).join('<br>'):'No comparable forecast change recorded in this edition.'}</p><a href="${esc(w.sourceUrl)}" target="_blank" rel="noopener noreferrer">Check the latest NWS forecast ↗</a></section>`;
 }
 function watch(games){const upcoming=games.filter(g=>Date.now()<Date.parse(g.kickoffAt));const forecasts=upcoming.filter(g=>g.weather?.status==='FORECAST'&&g.weather.roof==='OUTDOOR').sort((a,b)=>(b.weather.windMph-a.weather.windMph)||(b.weather.precipProbability-a.weather.precipProbability));const selected=forecasts.slice(0,3);const missing=upcoming.filter(g=>g.weather?.status==='UNAVAILABLE').length;
 return `<section class="panel mini weather-watch"><p class="eyebrow">THE WEATHER DESK</p><h3>Weather worth watching</h3><p>Highest forecast sustained winds among upcoming outdoor games in this edition. Ranking is for research attention, not betting value.</p><div class="guide-highlights">${selected.map(g=>`<a href="guide.html#game-${esc(g.id)}"><b>${esc(g.away)} at ${esc(g.home)}</b><p>${esc(g.weather.windMph)} mph peak sustained · ${esc(g.weather.precipProbability)}% peak hourly precipitation chance</p><small>${esc(state(g))} · issued ${esc(when(g.weather.issuedAt))}</small></a>`).join('')||'<p>No upcoming outdoor forecasts available.</p>'}</div><p>${missing} upcoming games lack a verified forecast. Roof status, temperature, sources and collection times appear in each matchup.</p><a href="guide.html">See all game conditions →</a></section>`;
 }
 window.StatPigWeather={panel,watch,state};
 setInterval(()=>document.querySelectorAll('[data-weather-status]').forEach(el=>{const g=window.StatPigGuide?.games.find(g=>g.id===el.dataset.weatherStatus);if(g)el.textContent=state(g);}),30000);
})();
